yarnPath: .yarn/releases/yarn-3.2.3.cjs

packageExtensions:
  eslint-plugin-flowtype@*:
    dependencies:
      "@babel/core": "*"
      "@babel/plugin-syntax-flow": "*"
      "@babel/plugin-transform-react-jsx": "*"
